import json

# 23 sites from internal tracker. Status mapping for public site:
# GIGA-42 Responsibility -> live (3)
# Development focus -> tbd published (5)
# Later stage / Lead *hot* / future -> tbd unpublished (kept in CMS)
# Going to 3rd party / Bin / WTF -> unpublished
sites = [
    # GIGA-42 / live (operating + active development we own)
    {"id":"glomfjord","name":"Glomfjord","country":"Norway","status":"live","lat":66.8167,"lng":13.9667,"power":"Hydro","initial_mw":"30 MW","target_mw":"50 MW+","image":"glomfjord.webp","desc_en":"Operating site. Hydropower-rich coastal location, modular expansion to 50 MW+ campus.","desc_no":"Driftslokasjon. Vannkraftrik kyst, modulær utvidelse til 50 MW+ campus.","published":True,"internal_status":"Project — Operating","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"bakki","name":"Bakki","country":"Iceland","status":"live","lat":66.05,"lng":-17.35,"power":"Geothermal","initial_mw":"50 MW","target_mw":"200 MW","image":"bakki.jpg","desc_en":"Geothermal baseload site, Phase 1 50 MW (2027), scaling to 200 MW.","desc_no":"Geotermisk grunnlast, fase 1 50 MW (2027), skalerer til 200 MW.","published":True,"internal_status":"Project — Develop","internal_category":"Develop / Dispose","internal_owner":"GIGA-42 50/50"},
    {"id":"skibotn","name":"Skibotn","country":"Norway","status":"tbd","lat":69.38,"lng":20.27,"power":"Hydro","initial_mw":"7 MW","target_mw":"15 MW","image":"","desc_en":"Mixed brownfield site near the Far North Fibre landing point.","desc_no":"Brownfield-lokasjon nær Far North Fibre-landingspunktet.","published":True,"internal_status":"Project — Develop","internal_category":"Develop / Mining or Dispose","internal_owner":"GIGA-42 45/55 (can move to 50/50)"},
    {"id":"reykjavik","name":"Reykjavík","country":"Iceland","status":"tbd","lat":64.0,"lng":-21.18,"power":"Geothermal","initial_mw":"30 MW","target_mw":"200 MW","image":"","desc_en":"GIGA-42 lead. Powered land partnership with Reykjavík Energy in Ölfus.","desc_no":"GIGA-42 prosjekt. Avtaleforhandlinger med Reykjavík Energy i Ölfus.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"GIGA-42 50/50"},

    # Development focus / publishable as tbd
    {"id":"varkaus","name":"Varkaus","country":"Finland","status":"tbd","lat":62.3167,"lng":27.8833,"power":"Mixed renewable","initial_mw":"","target_mw":"50 MW+","image":"varkaus.jpg","desc_en":"Industrial-ready Finnish site with strong municipal backing. Construction targeted 2026.","desc_no":"Industriklar finsk lokasjon med sterk kommunal støtte. Byggestart 2026.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"kristinestad","name":"Kristinestad","country":"Finland","status":"tbd","lat":62.27,"lng":21.38,"power":"Mixed renewable","initial_mw":"60 MW","target_mw":"800 MW","image":"","desc_en":"Vast site with phased grid integration; municipal backing secured.","desc_no":"Stor lokasjon med faset nettilkobling; kommunal støtte sikret.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"nivala","name":"Nivala","country":"Finland","status":"tbd","lat":63.93,"lng":24.95,"power":"Hydro / mixed","initial_mw":"50 MW","target_mw":"400 MW","image":"","desc_en":"400 kV substation adjacency. LOI with municipality, expansion to 500 MW+.","desc_no":"Tilstøtende 400 kV transformatorstasjon. LOI med kommunen, utvidelse til 500 MW+.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"jokkmokk","name":"Jokkmokk","country":"Sweden","status":"tbd","lat":66.6,"lng":19.83,"power":"Hydro","initial_mw":"50 MW","target_mw":"400 MW","image":"","desc_en":"Hydropower-anchored site adjacent to the 446 MW Miessaure dam. Partnership with Jokkmokk municipality.","desc_no":"Vannkraftforankret lokasjon nær Miessaure-demningen (446 MW). Partnerskap med Jokkmokk kommune.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"kronoby","name":"Kronoby","country":"Finland","status":"tbd","lat":63.72,"lng":23.02,"power":"Mixed renewable","initial_mw":"50 MW","target_mw":"400 MW","image":"","desc_en":"West coast Finland site, lease negotiations with Kronoby municipality.","desc_no":"Vestkyst-Finland, leieforhandlinger med Kronoby kommune.","published":True,"internal_status":"Project — Develop","internal_category":"Develop","internal_owner":"Scale42 100%"},

    # Internal-only / not publicly disclosed yet
    {"id":"liperi","name":"Liperi","country":"Finland","status":"tbd","lat":62.55,"lng":29.4,"power":"Mixed renewable","initial_mw":"60 MW","target_mw":"100 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Going to 3rd party","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"kitee","name":"Kitee","country":"Finland","status":"tbd","lat":62.1,"lng":30.13,"power":"Mixed renewable","initial_mw":"50 MW","target_mw":"60 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Going to 3rd party","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"honningsvag","name":"Honningsvåg","country":"Norway","status":"tbd","lat":70.98,"lng":25.97,"power":"Hydro","initial_mw":"8 MW","target_mw":"15 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Bin","internal_category":"Bin","internal_owner":"Scale42 90%"},
    {"id":"kemi","name":"Kemi","country":"Finland","status":"tbd","lat":65.74,"lng":24.56,"power":"Mixed renewable","initial_mw":"45 MW","target_mw":"1000 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Mining or Dispose","internal_category":"Mining/Dispose","internal_owner":"GIGA-42 50/50"},
    {"id":"mikkeli","name":"Mikkeli","country":"Finland","status":"tbd","lat":61.69,"lng":27.27,"power":"Mixed renewable","initial_mw":"60 MW","target_mw":"250 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Bin","internal_category":"Bin","internal_owner":"Scale42 100%"},
    {"id":"sorfold","name":"Sørfold","country":"Norway","status":"tbd","lat":67.47,"lng":15.45,"power":"Hydro","initial_mw":"50 MW","target_mw":"100 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Project — Going to 3rd party","internal_category":"Dispose","internal_owner":"Scale42 79%"},
    {"id":"torsboda","name":"Torsboda","country":"Sweden","status":"tbd","lat":62.55,"lng":17.6,"power":"Mixed renewable","initial_mw":"250 MW","target_mw":"1200 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead — hot","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"alajarvi","name":"Alajärvi","country":"Finland","status":"tbd","lat":63.0,"lng":23.81,"power":"Mixed renewable","initial_mw":"50 MW","target_mw":"1000 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Develop","internal_owner":"Scale42 100%"},
    {"id":"boden","name":"Boden","country":"Sweden","status":"tbd","lat":65.83,"lng":21.69,"power":"Hydro","initial_mw":"50 MW","target_mw":"1000 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Develop / Close","internal_owner":"Scale42 100%"},
    {"id":"robertsfors","name":"Robertsfors","country":"Sweden","status":"tbd","lat":64.18,"lng":20.83,"power":"Mixed renewable","initial_mw":"70 MW","target_mw":"280 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Later stage","internal_owner":"GIGA-42 50/50"},
    {"id":"hadsel","name":"Hadsel","country":"Norway","status":"tbd","lat":68.55,"lng":14.85,"power":"Hydro","initial_mw":"20 MW","target_mw":"40 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Bin","internal_owner":"Scale42 90%"},
    {"id":"sortland","name":"Sortland","country":"Norway","status":"tbd","lat":68.7,"lng":15.42,"power":"Hydro","initial_mw":"20 MW","target_mw":"40 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Bin","internal_owner":"Scale42 90%"},
    {"id":"tjeldbergodden","name":"Tjeldbergodden","country":"Norway","status":"tbd","lat":63.42,"lng":8.55,"power":"Hydro","initial_mw":"30 MW","target_mw":"190 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Develop or Mining","internal_owner":"In negotiations"},
    {"id":"salsbruket","name":"Salsbruket","country":"Norway","status":"tbd","lat":64.81,"lng":11.96,"power":"Hydro","initial_mw":"5 MW","target_mw":"80 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Mining/Close","internal_owner":"Scale42 100%"},
    {"id":"rovaniemi","name":"Rovaniemi","country":"Finland","status":"tbd","lat":66.5,"lng":25.72,"power":"Hydro","initial_mw":"50 MW","target_mw":"800 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Dispose/Close/Mining","internal_owner":"Scale42 100%"},
    {"id":"nuuk","name":"Nuuk","country":"Greenland","status":"tbd","lat":64.18,"lng":-51.74,"power":"Hydro","initial_mw":"30 MW","target_mw":"55 MW","image":"","desc_en":"","desc_no":"","published":False,"internal_status":"Lead","internal_category":"Later stage","internal_owner":"GIGA-42 50/50"},
]

json.dump({"sites": sites}, open('content/sites.json','w',encoding='utf-8'), indent=2, ensure_ascii=False)
print('sites:', len(sites), 'public:', sum(1 for s in sites if s['published']))

# 6 more news drafts
news = json.load(open('content/news.json',encoding='utf-8'))
extra = [
    {"slug":"prefab-acceleration","type_en":"Capabilities","type_no":"Kapabiliteter","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"Pre-fabricated modular DC unit","title_en":"Pre-fab acceleration: from foundation to live cluster in 9 months","title_no":"Prefab-akselerasjon: fra fundament til drift på 9 måneder","excerpt_en":"How factory-built modules collapse the schedule between site selection and customer go-live, and why the supply-chain economics now favour prefab over stick-built halls.","excerpt_no":"Hvordan fabrikkbygde moduler kutter tiden mellom lokasjonsvalg og kundedrift — og hvorfor leverandørkjede-økonomien nå favoriserer prefab fremfor pinnebygd.","featured":False,"published":False},
    {"slug":"sovereign-european-compute","type_en":"Strategy","type_no":"Strategi","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"European data sovereignty","title_en":"Sovereign AI compute: why European workloads are following European power","title_no":"Suveren KI-beregning: hvorfor europeiske arbeidslaster følger europeisk kraft","excerpt_en":"Regulators, customers and capital now treat where the silicon sits as a first-class concern. The Nordics are the natural answer for any workload that has to remain inside European jurisdictional control.","excerpt_no":"Regulatorer, kunder og kapital behandler nå hvor silisiumet ligger som en førsteklasses bekymring. Norden er det naturlige svaret for arbeidslaster som må holdes innenfor europeisk jurisdiksjon.","featured":False,"published":False},
    {"slug":"dlc-30kw-threshold","type_en":"Operations","type_no":"Drift","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"Direct liquid cooling manifold","title_en":"DLC at 30 kW per rack: when liquid stops being optional","title_no":"DLC på 30 kW per rack: når væske slutter å være valgfritt","excerpt_en":"Above 30 kW per rack the air-side plant becomes the bottleneck. We map the inflection where liquid cooling stops being a customer preference and starts being a site design constraint.","excerpt_no":"Over 30 kW per rack blir luftsiden flaskehalsen. Vi kartlegger vendepunktet der væskekjøling slutter å være en kundepreferanse og blir en designforutsetning.","featured":False,"published":False},
    {"slug":"effective-pue-greenfield","type_en":"Engineering","type_no":"Ingeniørfag","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"PUE measurement on greenfield site","title_en":"How we forecast effective PUE at greenfield sites","title_no":"Slik prognoserer vi effektiv PUE på greenfield-lokasjoner","excerpt_en":"PUE forecasts done badly fail closed; done well, they de-risk the customer's TCO model. Our approach combines climate data, plant-level modelling, and ten years of on-site measurement.","excerpt_no":"PUE-prognoser gjort dårlig feiler lukket; gjort godt avlaster de kundens TCO-modell. Vår metode kombinerer klimadata, anleggsmodellering og ti års feltmålinger.","featured":False,"published":False},
    {"slug":"heat-reuse-aquaculture","type_en":"Sustainability","type_no":"Bærekraft","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"Aquaculture facility receiving DC heat","title_en":"Heat-reuse: pairing data centre output with Nordic aquaculture","title_no":"Varmegjenvinning: kobling av datasenter-utgang med nordisk akvakultur","excerpt_en":"The Salsbruket model — surplus power, surplus heat, fish farm next door. Why heat off-take is no longer a footnote in the planning permission and is becoming a structural part of how we site campuses.","excerpt_no":"Salsbruket-modellen — overskuddskraft, overskuddsvarme, fiskefarm ved siden av. Hvorfor varmeavtak ikke lenger er en fotnote i reguleringen, men strukturell del av hvordan vi planlegger campus.","featured":False,"published":False},
    {"slug":"year-in-review-2026","type_en":"Year in review","type_no":"Året i tilbakeblikk","date_en":"DRAFT","date_no":"UTKAST","image":"","alt":"Scale42 2026 review","title_en":"Year in review 2026","title_no":"Året 2026 i tilbakeblikk","excerpt_en":"Sites secured, capacity contracted, customers onboarded — the 2026 progress against the pipeline thesis. Annual recap to publish in December.","excerpt_no":"Sikrede lokasjoner, kontrahert kapasitet, kunder ombord — 2026 fremdrift mot pipeline-tesen. Årlig oppsummering for desember-publisering.","featured":False,"published":False},
]
news['posts'] = news['posts'] + extra
json.dump(news, open('content/news.json','w',encoding='utf-8'), indent=2, ensure_ascii=False)
print('news posts:', len(news['posts']))
